input {
  beats {
    port => 5044
  }
}

output {
  elasticsearch {
    hosts => ["https://localhost:9200"]
    index => "%{[@metadata][beat]}-%{[@metadata][version]}"
    user => "{{ lookup('aws_ssm', 'elasticsearch.master_username', region='us-east-1' ) }}"
    password => "{{ lookup('aws_ssm', 'elasticsearch.master_password', region='us-east-1' ) }}"
    ssl_certificate_verification => false
    ssl => true

  }
}