- name: Install Maven
  ansible.builtin.dnf:
    name: maven
    state: latest

- name: Import App Pre requisites
  ansible.builtin.import_tasks: app-preq.yml

- name: Download Maven Dependencies
  ansible.builtin.shell: mvn clean package ; mv target/${component}-1.0.jar ${component}.jar
  args:
    chdir: /app

- name: Import Schema
  ansible.builtin.import_tasks: mysql-schema.yml
  when: schema is defined

- name: SystemD Service
  ansible.builtin.import_tasks: systemd.yml

