- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Create RoboShop Conf File - Project Config
  ansible.builtin.copy:
    src: nginx-roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Create Nginx Conf File - Main Config
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name:  Remove Directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create Directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

#- name: Download File and Extract Content
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
#    dest: /usr/share/nginx/html
#    remote_src: yes

- name: Download File and Extract Content from Nexus
  ansible.builtin.unarchive:
    src: http://{{username}}:{{password}}@172.31.243:8081/repository/{{component}}/{{component}}-{{appVersion}}.zip
    dest: /app
    remote_src: yes

    vars:
      username: "{{ lookup('aws_ssm', 'nexus.username', region='us-east-1' ) }}"
      password: "{{ lookup('aws_ssm', 'nexus.password', region='us-east-1' ) }}"
      appVersion: "{{ lookup('aws_ssm', '{{component}}.{{env}}.{{appVersion}}', region='us-east-1' ) }}"

- name: Start Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: Create Prometheus Nginx Expoter Directory
  ansible.builtin.file:
    path: /opt/nginx_exporter
    state: directory

- name: Download Prometheus Nginx Exporter
  ansible.builtin.unarchive:
    src: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.11.0/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz
    dest: /opt/nginx_exporter
    remote_src: yes

- name: Create Prometheus Nginx Exporter Service Configuration
  ansible.builtin.copy:
    src: nginx-exporter.service
    dest: /etc/systemd/system/nginx_exporter.service

- name: Restart Prometheus Nginx Service
  ansible.builtin.systemd:
    name: nginx_exporter
    state: restarted
    enabled: yes

- name: Setup Filebeat
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat