- name: Install MySQL
  ansible.builtin.dnf:
    name: mysql
    state: latest

- name: Load MySQL Schema
  ansible.builtin.shell: mysql -h {{ lookup('aws_ssm', '{{component}}.{{env}}.DB_HOST', region='us-east-1' ) }} -u{{ lookup('aws_ssm', 'rds.{{env}}.master_username', region='us-east-1' ) }} -p{{ lookup('aws_ssm', 'rds.{{env}}.master_password', region='us-east-1' ) }} < /app/schema/{{component}}.sql

